chart/browserless-chrome:
  - changed-files:
    -  any-glob-to-any-file: 'charts/browserless-chrome/**/*'

chart/caddy:
  - changed-files:
    -  any-glob-to-any-file: 'charts/caddy/**/*'

chart/dex-k8s-authenticator:
  - changed-files:
    -  any-glob-to-any-file: 'charts/dex-k8s-authenticator/**/*'

chart/kube-secrets-init:
  - changed-files:
    -  any-glob-to-any-file: 'charts/kube-secrets-init/**/*'

chart/rabbitmq-operator:
  - changed-files:
    -  any-glob-to-any-file: 'charts/rabbitmq-operator/**/*'

chart/sftpgo:
  - changed-files:
    -  any-glob-to-any-file: 'charts/sftpgo/**/*'

chart/tusd:
  - changed-files:
    -  any-glob-to-any-file: 'charts/tusd/**/*'
